In [1]:
import numpy as np

import src

In [2]:
src.gini(np.array([0, 1, 2, 3, 4]))

0.8000000000000002

In [3]:
src.weighted_impurity(np.array([0, 1, 2, 3]), np.array([0, 1, 3, 4]))

(0.75, 0.75, 0.75)

In [4]:
data_path = '../kaggle_4/data'

In [5]:
import os
os.listdir(data_path)

['lh.csv',
 'test.csv',
 'items.csv',
 'train.csv',
 'events.csv',
 'xp.csv',
 'competition-yandex-shad-autumn-2024.zip',
 'heroes.csv',
 'gold.csv']

In [6]:
y = np.array([0, 1, 3, 4, 6, 7, 3, 4, 5])

left_idx, right_idx = src.create_split(y, 3)

left_idx, right_idx

(array([0, 1, 2, 6]), array([3, 4, 5, 7, 8]))

In [7]:
src.create_split(y, 3)

(array([0, 1, 2, 6]), array([3, 4, 5, 7, 8]))

In [8]:
src.weighted_impurity(y[left_idx], y[right_idx])

(0.6777777777777778, 0.625, 0.7200000000000001)

In [9]:
y[left_idx]

array([0, 1, 3, 3])

In [29]:
(y == 3).sum()

2

In [10]:
from scipy.stats import mode

In [33]:
mode(np.array([0, 0, 1, 1]))[0]

0

In [15]:
X = np.array([
    [0, 1],
    [2, 3]
])

In [51]:
X[0, :] = [-1, -1]

In [52]:
X

array([[-1, -1],
       [ 2,  3]])

In [43]:
X.mean(axis=0).shape

(2,)

In [23]:
X[0:1, :]

array([[0, 1]])

In [25]:
x = None

In [26]:
x + 1

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

In [38]:


indices = np.random.randint(0, y.shape[0], y.shape[0])

In [39]:
indices

array([7, 5, 3, 5, 3, 7, 0, 2, 3])

In [40]:
y

array([0, 1, 3, 4, 6, 7, 3, 4, 5])